
name: foo bar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  foo1:
    if: ${{ !contains($GITHUB_REF_NAME, 'rc') }}
    runs-on: ubuntu-latest
    steps:
      - name: generate output
        id: generate-output
#         run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
#         run: echo "{tag}=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT"
    outputs:
      foo1-output: ${{ steps.generate-output.outputs.tag }}
  foo2:
    needs: foo1
    runs-on: ubuntu-latest
#     if: ${{ !contains(needs.foo1.outputs.foo1-output, 'rc') }}
    steps:
      - name: print foo1 output
        env:
          foo1_OUTPUT: ${{ needs.foo1.outputs.foo1-output }}
        run: echo "$foo1_OUTPUT"
