
name: foo bar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  foo1:
    strategy:
      matrix:
        platform:
          - kinesis
          - sqs
          - pubsub
          - kafka
          - nsq
          - stdout
          - rabbitmq
    if: ${{ !contains(github.ref, 'rc') }}
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.ref: ${{  github.ref }}"
      - name: Check if Snyk should run
        id: shouldRunSnyk
        run: echo "{shouldRunSnyk}={!contains(github.ref_name, 'rc') && contains(fromJson('["kinesis", "pubsub"]'), matrix.platform)}" >> $GITHUB_OUTPUT
      - name: Prints what shouldrunsnyk is
        id: boolPrinter
        run: echo "${{ steps.shouldRunSnyk.outputs.shouldRunSnyk }}"
      - name: Just prints if the if condition passes
        if: ${{ steps.shouldRunSnyk.outputs.shouldRunSnyk }}
        run: echo 'hello world!'
      - name: Just prints if the MANUAL if condition passes
        if: ${{ !contains(github.ref_name, 'rc') && contains(fromJson('["kinesis", "pubsub"]'), matrix.platform) }}
        run: echo 'hello world!'
