
name: foo bar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  foo1:
    strategy:
      matrix:
        platform:
          - kinesis
          - sqs
          - pubsub
          - kafka
          - nsq
          - stdout
          - rabbitmq
        include:
#           - run_snyk: false
          - platform: kinesis
            run_snyk: ${{!contains(github.ref, 'rc')}}
          - platform: pubsub
            run_snyk: ${{!contains(github.ref, 'rc') }}
#     if: ${{ !contains(github.ref, 'rc') }}
    env: 
      RUN_SNYK: ${{ !contains(github.ref_name, 'rc') && contains(fromJson('["kinesis", "pubsub"]'), matrix.platform) }}
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github.ref: ${{  github.ref }}"
      - name: Check if Snyk should run
        id: shouldRunSnyk
        run: echo $RUN_SNYK
      - name: Get current version
        id: ver
        run: |
          export PROJECT_VERSION=25
          echo "{project_version}={}" "::set-output name=project_version::$PROJECT_VERSION"
      - name: Print prohject versipon plz
        run: echo ${{ steps.ver.outputs.project_version }}
      - name: Just prints if the MATRIX if condition passes
        if: matrix.run_snyk
        run: echo 'hello world! the matrix check is workin'
